import ContactForm from "@/components/ContactForm";
import { contactInfos } from "@/data";
import Head from "next/head";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import clsx from "clsx";
import BottomDots from "@/components/BottomDots";

export const metadata: Metadata = {
    title: "Contacter nous - Logo",
    description: "Generated by create next app",
  };

export default function ContactPage() {
  return (
    <main>
      <Head>
        <title>Lancez votre site web | Contacter nous - Logo</title>
        <meta key={"description"} content="This contact us page" />
      </Head>
      <article className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pt-36 text-dark-secondary">
        <div className="grid md:grid-cols-2 gap-10">
          <section className="flex flex-col">
            <div>
              <h1 className="text-2xl md:text-4xl md:leading-[130%] text-dark-primary font-semibold mb-6">
                Contactez-nous pour lancer votre site web
              </h1>
              <p className="text-lg leading-7 mb-8">
                Collaborez avec nous pour votre prochain projet web et prenez un
                avantage sur le marché. Remplissez simplement le formulaire et
                partagez votre vision. Nous sommes là pour transformer vos idées
                en une expérience digitale exceptionnelle qui vous démarquera de
                la concurrence.
              </p>
            </div>

            <div className="space-y-4 mt-auto">
              {contactInfos.map((item, index) => (
                <div
                  key={item.label}
                  className="flex items-center gap-4 p-4 rounded-md bg-mid-tone"
                >
                  <Image src={item.iconPath} alt="" width={32} height={32} />
                  <p className="text-lg text-dark-primary font-semibold">
                    {item.label}
                  </p>
                </div>
              ))}
            </div>
          </section>
          <ContactForm />
        </div>
        <section className="mt-16">
          <h2 className="text-xl md:text-2xl font-semibold text-dark-primary">
            Pas encore prêt à nous contacter ? Explorez nos services ou
            consultez notre FAQ.
          </h2>

          <ul className="mt-4 space-y-2 text-dark-primary">
            <li className="relative block pl-10 group">
              <Image
                className="absolute left-0 group-hover:ml-2 transition-all duration-200 ease-in-out"
                src={"/icons/link.svg"}
                alt=""
                width={28}
                height={28}
              />
              <Link
                href={"/services"}
                className={clsx(
                  "relative w-fit block after:block after:content-[''] after:absolute after:h-[2px] after:bg-highlight after:w-full after:scale-x-0 after:hover:scale-x-100 after:transition after:duration-300 after:origin-right after:hover:origin-left text-center text-3xl text-lg"
                )}
              >
                Nos Services
              </Link>
            </li>
            <li className="relative block pl-10 group">
              <Image
                className="absolute left-0 group-hover:ml-2 transition-all duration-200 ease-in-out"
                src={"/icons/link.svg"}
                alt=""
                width={28}
                height={28}
              />
              <Link
                href={"/faq"}
                className={clsx(
                  "relative w-fit block after:block after:content-[''] after:absolute after:h-[2px] after:bg-highlight after:w-full after:scale-x-0 after:hover:scale-x-100 after:transition after:duration-300 after:origin-right after:hover:origin-left text-center text-3xl text-lg"
                )}
              >
                Questions Fréquemment Posées
              </Link>
            </li>
          </ul>
        </section>
        <BottomDots />
      </article>
    </main>
  );
}
