import type { Metadata } from "next";
import "./globals.css";
import "./reset.css";
import { bodyFont, headingFont } from "@/lib/fonts";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${bodyFont.variable} ${headingFont.variable} font-body bg-light`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
